FROM golang:1.22.8-alpine AS builder

WORKDIR /app

COPY main.go .
COPY go.mod .
COPY go.sum .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o webhook-server main.go

FROM scratch

WORKDIR /app

USER 1000

COPY --from=builder /app/webhook-server /app/webhook-server
EXPOSE 8443 9999
