---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-mlmodels
  namespace: mlmm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: get-mlmodels
subjects:
- kind: ServiceAccount
  name: get-mlmodels
  namespace: mlmm
