---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: mlmm
spec:
  type: NodePort
  selector:
    app: nginx-pod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  externalTrafficPolicy: Local