apiVersion: nedo.com/v1
kind: MLModel
metadata:
  name: nedo-mecsvr01
  namespace: mlmm
redfish:
  host: 192.168.0.121
  port: 443
machineLearningModels:
  powerConsumptionModel:
    name: PC-PowerEdgeR650xs-2CPU
    url: http://x.x.x.x
    type: V2InferenceProtocol
    version: v0.1.0
  responseTimeModel:
    name: RT-PowerEdgeR650xs-2CPU
    url: http://x.x.x.x
    type: V2InferenceProtocol
    version: v0.1.0