apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader-role
  namespace: waok8s-webhook
rules:
- apiGroups:
  - ""
  resourceNames:
  - harbor-secret
  resources:
  - secrets
  verbs:
  - get
