apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-rolebinding
  namespace: waok8s-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-reader-role
subjects:
- kind: ServiceAccount
  name: secret-reader
  namespace: waok8s-webhook
